
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int RBRACK = 11;
  public static final int IDENT = 19;
  public static final int SEMICOLON = 7;
  public static final int ELSE = 6;
  public static final int PLUS = 15;
  public static final int RBRACE = 13;
  public static final int RPAREN = 9;
  public static final int INT = 2;
  public static final int LBRACK = 10;
  public static final int RETURN = 4;
  public static final int INTCONST = 17;
  public static final int IF = 5;
  public static final int LPAREN = 8;
  public static final int LBRACE = 12;
  public static final int EOF = 0;
  public static final int DOUBLECONST = 18;
  public static final int error = 1;
  public static final int ASSIGN = 14;
  public static final int MUL = 16;
  public static final int DOUBLE = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "DOUBLE",
  "RETURN",
  "IF",
  "ELSE",
  "SEMICOLON",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "LBRACE",
  "RBRACE",
  "ASSIGN",
  "PLUS",
  "MUL",
  "INTCONST",
  "DOUBLECONST",
  "IDENT"
  };
}

