
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVIDE = 23;
  public static final int GREATERTHENEQUAL = 33;
  public static final int LESSTHEN = 30;
  public static final int MULASSIGN = 27;
  public static final int NOTEQUAL = 35;
  public static final int DOUBLE = 3;
  public static final int LPAREN = 13;
  public static final int INT = 2;
  public static final int FOR = 8;
  public static final int RPAREN = 14;
  public static final int PLUSASSIGN = 25;
  public static final int LESSTHENEQUAL = 31;
  public static final int NOT = 12;
  public static final int SEMICOLON = 10;
  public static final int INTCONST = 36;
  public static final int DOUBLECONST = 37;
  public static final int EQUALEQUAL = 34;
  public static final int DIVIDEASSIGN = 28;
  public static final int PLUS = 20;
  public static final int ASSIGN = 19;
  public static final int IF = 5;
  public static final int EOF = 0;
  public static final int RETURN = 4;
  public static final int error = 1;
  public static final int MUL = 21;
  public static final int MODULO = 24;
  public static final int IDENT = 38;
  public static final int SUBASSIGN = 26;
  public static final int LBRACK = 15;
  public static final int COLON = 11;
  public static final int GREATERTHEN = 32;
  public static final int LBRACE = 17;
  public static final int ELSE = 6;
  public static final int RBRACK = 16;
  public static final int GOTO = 9;
  public static final int WHILE = 7;
  public static final int RBRACE = 18;
  public static final int MODULOASSIGN = 29;
  public static final int SUB = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "DOUBLE",
  "RETURN",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "GOTO",
  "SEMICOLON",
  "COLON",
  "NOT",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "LBRACE",
  "RBRACE",
  "ASSIGN",
  "PLUS",
  "MUL",
  "SUB",
  "DIVIDE",
  "MODULO",
  "PLUSASSIGN",
  "SUBASSIGN",
  "MULASSIGN",
  "DIVIDEASSIGN",
  "MODULOASSIGN",
  "LESSTHEN",
  "LESSTHENEQUAL",
  "GREATERTHEN",
  "GREATERTHENEQUAL",
  "EQUALEQUAL",
  "NOTEQUAL",
  "INTCONST",
  "DOUBLECONST",
  "IDENT"
  };
}

